#!/usr/bin/env bash
# ============================================================
# fix.sh — Review approved issues and apply fixes
#
# Reads ./reports/approved.txt (generated by test.sh) and:
#   1. Prints each approved issue clearly
#   2. Generates a specific fix description for each
#   3. Prompts to apply fixes
#   4. If yes — applies fixes, rebuilds, and re-runs test.sh
#   5. If no — exits cleanly
#
# Usage: ./fix.sh
# ============================================================

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/config.sh"

# ---- Colors ----
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log_info()  { echo -e "${CYAN}[INFO]${NC} $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# ============================================================
# Step 1: Validate inputs
# ============================================================
if [ ! -f "$APPROVED_FILE" ]; then
    log_error "No approved issues found. Run ./test.sh first."
    exit 1
fi

if [ ! -s "$APPROVED_FILE" ]; then
    log_error "$APPROVED_FILE is empty. No issues to fix."
    exit 1
fi

if [ ! -f "$REPORT_FILE" ]; then
    log_error "Report file not found at $REPORT_FILE. Run ./test.sh first."
    exit 1
fi

# ============================================================
# Step 2: Display approved issues
# ============================================================
echo -e "\n${BOLD}=== Approved Issues for Review ===${NC}\n"

# Initialize fixes file
rm -f "$FIXES_FILE"
touch "$FIXES_FILE"

while IFS= read -r issue_num; do
    # Skip empty lines
    [ -z "$issue_num" ] && continue

    echo -e "${BOLD}--- Issue #${issue_num} ---${NC}"

    # Extract the issue block from report.txt
    ISSUE_BLOCK=$(awk "/\\[Issue #${issue_num}\\]/,/^---$/" "$REPORT_FILE")

    if [ -z "$ISSUE_BLOCK" ]; then
        log_warn "Issue #$issue_num not found in report."
        continue
    fi

    echo "$ISSUE_BLOCK"
    echo ""

    # Extract issue fields
    ISSUE_TYPE=$(echo "$ISSUE_BLOCK" | grep "^Type:" | sed 's/^Type: //')
    ISSUE_SCREEN=$(echo "$ISSUE_BLOCK" | grep "^Screen:" | sed 's/^Screen: //')
    ISSUE_DESC=$(echo "$ISSUE_BLOCK" | grep "^Description:" | sed 's/^Description: //')
    ISSUE_SEVERITY=$(echo "$ISSUE_BLOCK" | grep "^Severity:" | sed 's/^Severity: //')

    # ============================================================
    # Step 3: Generate fix description based on issue type
    # ============================================================
    FIX_DESC=""

    # Parse element-specific info from enriched [ISSUE] output
    ELEMENT_ID=$(echo "$ISSUE_DESC" | grep -oP 'id:"[^"]*"' | head -1 | sed 's/id:"//;s/"//')
    ELEMENT_TYPE=$(echo "$ISSUE_DESC" | grep -oP 'type:"[^"]*"' | head -1 | sed 's/type:"//;s/"//')
    ELEMENT_BOUNDS=$(echo "$ISSUE_DESC" | grep -oP 'bounds:"[^"]*"' | head -1 | sed 's/bounds:"//;s/"//')

    # Build element reference for fix descriptions
    if [ -n "$ELEMENT_ID" ] && [ "$ELEMENT_ID" != "no-id" ]; then
        ELEMENT_REF="element '$ELEMENT_ID' ($ELEMENT_TYPE)"
        ELEMENT_XML_HINT="Find this element by its android:id=\"@+id/$(echo "$ELEMENT_ID" | sed 's/.*:id\///')\" in your layout XML."
    elif [ -n "$ELEMENT_TYPE" ]; then
        ELEMENT_REF="$ELEMENT_TYPE at bounds [$ELEMENT_BOUNDS]"
        ELEMENT_XML_HINT="Locate this $ELEMENT_TYPE by its position ($ELEMENT_BOUNDS) in the layout hierarchy."
    else
        ELEMENT_REF=""
        ELEMENT_XML_HINT=""
    fi

    case "$ISSUE_TYPE" in
        Crash)
            if echo "$ISSUE_DESC" | grep -qi "NullPointerException"; then
                FIX_DESC="Add null-safety check before the object access that caused the NPE. Use Kotlin safe-call operator (?.) or add a null guard."
            elif echo "$ISSUE_DESC" | grep -qi "ANR"; then
                FIX_DESC="Move the blocking operation off the main thread. Use coroutines (Dispatchers.IO) or a background executor for long-running work."
            elif echo "$ISSUE_DESC" | grep -qi "IllegalStateException"; then
                FIX_DESC="Check lifecycle state before performing the operation. Ensure the activity/fragment is in the correct state."
            else
                FIX_DESC="Investigate the crash stack trace in logcat. Add proper error handling and null checks around the failing code path."
            fi
            ;;
        Focus)
            if echo "$ISSUE_DESC" | grep -qi "no.*focus\|has focus"; then
                FIX_DESC="Add android:focusable=\"true\" and android:focusableInTouchMode=\"true\" to the view."
                [ -n "$ELEMENT_REF" ] && FIX_DESC="$FIX_DESC Target: $ELEMENT_REF. $ELEMENT_XML_HINT"
                FIX_DESC="$FIX_DESC Set android:nextFocusDown/Up/Left/Right for explicit focus order."
            elif echo "$ISSUE_DESC" | grep -qi "visible.*focus\|focus.*state"; then
                FIX_DESC="Add a focused-state drawable selector: <selector> with <item android:state_focused=\"true\"> that changes background/border when focused."
                [ -n "$ELEMENT_REF" ] && FIX_DESC="$FIX_DESC Apply to: $ELEMENT_REF. $ELEMENT_XML_HINT"
            elif echo "$ISSUE_DESC" | grep -qi "dialog\|return"; then
                FIX_DESC="Save focused view reference before showing dialog. In dialog dismiss callback, call savedView.requestFocus() to restore focus."
            else
                FIX_DESC="Ensure all interactive elements have android:focusable=\"true\" and a visible focus indicator drawable."
                [ -n "$ELEMENT_REF" ] && FIX_DESC="$FIX_DESC Check: $ELEMENT_REF. $ELEMENT_XML_HINT"
            fi
            ;;
        Navigation)
            if echo "$ISSUE_DESC" | grep -qi "trap\|stuck\|dead.end"; then
                FIX_DESC="Focus trap detected."
                [ -n "$ELEMENT_REF" ] && FIX_DESC="$FIX_DESC Trapped at $ELEMENT_REF. $ELEMENT_XML_HINT"
                # Parse which directions are blocked from the enriched output
                _blocked=$(echo "$ISSUE_DESC" | grep -oP 'Fix: add \K[^\]]*' | head -1)
                if [ -n "$_blocked" ]; then
                    FIX_DESC="$FIX_DESC Add missing attributes: $_blocked pointing to the correct neighbor views."
                else
                    FIX_DESC="$FIX_DESC Add nextFocusDown/Up/Left/Right attributes to connect this element to its neighbors."
                fi
            elif echo "$ISSUE_DESC" | grep -qi "tab"; then
                FIX_DESC="Set android:nextFocusLeft and android:nextFocusRight on tab items to enable horizontal D-pad navigation between tabs."
            elif echo "$ISSUE_DESC" | grep -qi "unreachable\|reachable"; then
                FIX_DESC="Unreachable elements detected. Add explicit nextFocusDown/Up/Left/Right attributes to ensure all focusable elements are connected in the D-pad navigation graph."
                [ -n "$ELEMENT_REF" ] && FIX_DESC="$FIX_DESC Unreachable: $ELEMENT_REF. $ELEMENT_XML_HINT"
            elif echo "$ISSUE_DESC" | grep -qi "one.way\|bidirectional\|asymmetric"; then
                FIX_DESC="One-way navigation link detected."
                [ -n "$ELEMENT_REF" ] && FIX_DESC="$FIX_DESC At: $ELEMENT_REF. $ELEMENT_XML_HINT"
                FIX_DESC="$FIX_DESC Ensure both elements reference each other with matching nextFocus* attributes (e.g., A.nextFocusDown=B and B.nextFocusUp=A)."
            elif echo "$ISSUE_DESC" | grep -qi "vertical\|up.*down\|down.*up"; then
                FIX_DESC="Set android:nextFocusUp and android:nextFocusDown on vertically arranged items. Consider using RecyclerView with proper focus handling."
            elif echo "$ISSUE_DESC" | grep -qi "spatial\|drift\|wrong.direction"; then
                FIX_DESC="Spatial navigation error — pressing a direction moves focus in the wrong direction."
                [ -n "$ELEMENT_REF" ] && FIX_DESC="$FIX_DESC At: $ELEMENT_REF. $ELEMENT_XML_HINT"
                FIX_DESC="$FIX_DESC Override nextFocus* attributes to force correct directional behavior, or fix the layout positioning so spatial navigation works naturally."
            else
                FIX_DESC="Review the D-pad navigation order. Add nextFocus* attributes or implement custom focus search logic in onKeyDown()."
            fi
            ;;
        UI|"UI Audit")
            if echo "$ISSUE_DESC" | grep -qi "small.*target\|touch.*target\|48.*dp\|48px"; then
                FIX_DESC="Focus target too small for comfortable D-pad use."
                [ -n "$ELEMENT_REF" ] && FIX_DESC="$FIX_DESC Element: $ELEMENT_REF. $ELEMENT_XML_HINT"
                FIX_DESC="$FIX_DESC Add android:minWidth=\"48dp\" android:minHeight=\"48dp\" or increase padding to meet the 48dp minimum."
            elif echo "$ISSUE_DESC" | grep -qi "overlap"; then
                FIX_DESC="Overlapping focusable elements cause unpredictable D-pad behavior."
                [ -n "$ELEMENT_REF" ] && FIX_DESC="$FIX_DESC Element: $ELEMENT_REF. $ELEMENT_XML_HINT"
                FIX_DESC="$FIX_DESC Fix layout constraints to prevent overlap, or set android:focusable=\"false\" on the decorative/background element."
            elif echo "$ISSUE_DESC" | grep -qi "response.*time\|slow\|latency"; then
                FIX_DESC="Slow response to D-pad input (>500ms). Move heavy work off the UI thread. Use View.post{} or coroutines for deferred updates."
            elif echo "$ISSUE_DESC" | grep -qi "truncat"; then
                FIX_DESC="Text truncation detected."
                [ -n "$ELEMENT_REF" ] && FIX_DESC="$FIX_DESC Element: $ELEMENT_REF. $ELEMENT_XML_HINT"
                FIX_DESC="$FIX_DESC Use android:ellipsize=\"end\" with android:maxLines, or increase the container width. For TV, ensure text is readable at 10-foot distance."
            elif echo "$ISSUE_DESC" | grep -qi "zero.size\|0x0\|invisible"; then
                FIX_DESC="Zero-size or invisible focusable element detected."
                [ -n "$ELEMENT_REF" ] && FIX_DESC="$FIX_DESC Element: $ELEMENT_REF. $ELEMENT_XML_HINT"
                FIX_DESC="$FIX_DESC Either give the element proper dimensions or set android:focusable=\"false\" if it shouldn't receive focus."
            elif echo "$ISSUE_DESC" | grep -qi "content.desc\|accessibility\|label"; then
                FIX_DESC="Missing accessibility label."
                [ -n "$ELEMENT_REF" ] && FIX_DESC="$FIX_DESC Element: $ELEMENT_REF. $ELEMENT_XML_HINT"
                FIX_DESC="$FIX_DESC Add android:contentDescription=\"descriptive text\" for screen reader support."
            elif echo "$ISSUE_DESC" | grep -qi "dialog"; then
                FIX_DESC="Ensure the dialog handles the BACK key correctly by setting dialog.setCancelable(true) or overriding onBackPressed()."
            elif echo "$ISSUE_DESC" | grep -qi "number\|numeric\|input"; then
                FIX_DESC="Set android:inputType=\"number\" on the input field and handle KEYCODE_0 through KEYCODE_9 in onKeyDown() or via an InputFilter."
            elif echo "$ISSUE_DESC" | grep -qi "rotation\|orientation"; then
                FIX_DESC="Focus lost after screen rotation. Save focus state in onSaveInstanceState() and restore in onRestoreInstanceState() using the view ID."
            elif echo "$ISSUE_DESC" | grep -qi "scroll.*position\|scroll.*restor"; then
                FIX_DESC="Scroll position not preserved. Save scroll position in onSaveInstanceState() and restore it. For RecyclerView, use layoutManager.onSaveInstanceState()/onRestoreInstanceState()."
            else
                FIX_DESC="Review the UI element behavior. Ensure proper event handling and state management for D-pad interaction."
                [ -n "$ELEMENT_REF" ] && FIX_DESC="$FIX_DESC Check: $ELEMENT_REF. $ELEMENT_XML_HINT"
            fi
            ;;
        Visual)
            FIX_DESC="Review the screenshot in ./reports/screenshots/ for visual anomalies. Check layout XML for proper constraints and margins."
            ;;
        *)
            FIX_DESC="Review the issue details and apply an appropriate fix."
            [ -n "$ELEMENT_REF" ] && FIX_DESC="$FIX_DESC Related element: $ELEMENT_REF. $ELEMENT_XML_HINT"
            ;;
    esac

    # Write fix to fixes file
    cat >> "$FIXES_FILE" <<EOF

[Fix for Issue #${issue_num}]
Type: ${ISSUE_TYPE}
Screen: ${ISSUE_SCREEN}
Severity: ${ISSUE_SEVERITY}
Problem: ${ISSUE_DESC}
Fix: ${FIX_DESC}
---
EOF

    echo -e "  ${GREEN}Suggested fix:${NC} $FIX_DESC"
    echo ""

done < "$APPROVED_FILE"

# ============================================================
# Step 4: Display all fixes
# ============================================================
echo -e "\n${BOLD}=== Generated Fix Descriptions ===${NC}\n"
cat "$FIXES_FILE"

log_ok "Fix descriptions saved to: $FIXES_FILE"

# ============================================================
# Step 5: Prompt to apply fixes
# ============================================================
echo ""
echo -e "${BOLD}Ready to apply fixes. Continue? (y/n)${NC}"
read -rp "> " apply_choice

case "$apply_choice" in
    y|Y|yes|YES)
        echo ""
        log_info "Applying fixes..."
        echo ""

        # For each fix, prompt the developer to make changes
        while IFS= read -r issue_num; do
            [ -z "$issue_num" ] && continue

            FIX_BLOCK=$(awk "/\\[Fix for Issue #${issue_num}\\]/,/^---$/" "$FIXES_FILE")
            FIX_LINE=$(echo "$FIX_BLOCK" | grep "^Fix:" | sed 's/^Fix: //')

            echo -e "${YELLOW}[Issue #${issue_num}]${NC} $FIX_LINE"
            echo -e "  ${CYAN}Please apply this fix in your source code, then press Enter to continue...${NC}"
            read -r
        done < "$APPROVED_FILE"

        # Rebuild and re-test
        echo ""
        log_info "Rebuilding and re-running tests..."
        echo ""

        exec "$SCRIPT_DIR/test.sh"
        ;;
    *)
        log_info "Exiting without applying fixes."
        log_info "Fix descriptions are saved in: $FIXES_FILE"
        exit 0
        ;;
esac
